### ISSUE TITLE
Procswap Not Opening Miner.

### ISSUE THREAD

**Issue by PeepsEZ** [billiford/procswap#5]
Describe the bug
Procswap is not opening the Phoenixminer bat file. It says start ok but doesn't actually open it. My command looks like this:
procswap.exe --priority E:\Steam\steamapps\common --swap C:\Users\Peeps\Downloads\Tools\PhoenixMiner\start_miner.bat

Screenshots
![delete](https://user-images.githubusercontent.com/14933388/105876056-90aa9e80-5fcc-11eb-93ed-dd143d70d968.jpg)

**Comment by billiford** [comment]
It's true that it's not opening the PhoenixMiner in another command prompt where you can see the output. However you should see `PhoenixMiner.exe` running in your Task Manager in Windows under the "Windows Command Processor".
<img width="998" alt="procswap-issue-1" src="https://user-images.githubusercontent.com/7597848/105882525-be471600-5fd3-11eb-9bf1-84a9738ab018.png">
This is because your batch file is being executing *inside* the running terminal. We need a better way to access the output of your miners.

I'm thinking of solving this one of two ways... either procswap will open up other terminals, or you can press a key while procswap is running to switch to the output of the commands running. I'm thinking the second will be easier for now.

PhoenixMiner additionally should be storing logs of what's happening next to `procswap.exe`.

**Comment by PeepsEZ** [comment]
This is how it looks when I start Procswap.

![delete 1](https://user-images.githubusercontent.com/14933388/105884136-a6709180-5fd5-11eb-995e-613ab0b8d06d.jpg)


This is what it looks like If I start Procswap, then manually open Phoenixminer, and then open a game.
![delete 2](https://user-images.githubusercontent.com/14933388/105885917-c6a15000-5fd7-11eb-959c-d456b3529944.jpg)

**Comment by billiford** [comment]
Huh, could you post the contents of your `start_miner.bat` file please?

**Comment by PeepsEZ** [comment]
REM
REM Example bat file for starting PhoenixMiner.exe to mine ETH
REM

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

REM IMPORTANT: Replace the ETH address with your own ETH wallet address in the -wal option (Rig001 is the name of the rig)
PhoenixMiner.exe -pool ssl://eth-us-east.flexpool.io:5555 -pool2 ssl://eth-us-west.flexpool.io:5555 -wal 0x37d5F7d290dd5509CF5e2C5257689Ddd5c53f78D.Rig001 -logdir C:\Users\Peeps\Downloads\Tools\PhoenixMiner\logs -logsmaxsize 50
pause

**Comment by billiford** [comment]
Give a full path to your `PhoenixMiner.exe`. The error killing process is because the process never started your PM (just as your issue originally stated, sorry!). When you run a `.bat` file like this from procswap it doesn't know the full path to PM which is why PM isn't starting. Let's see if this fixes it.

Try setting this as your `start_miner.bat` file. Please check that the path I guessed from your logs to PM exists. Make sure you double checking everything here. I didn't (but could) change that to my address so you're mining for me lol
```
REM
REM Example bat file for starting PhoenixMiner.exe to mine ETH
REM

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100

REM IMPORTANT: Replace the ETH address with your own ETH wallet address in the -wal option (Rig001 is the name of the rig)
C:\Users\Peeps\Downloads\Tools\PhoenixMiner\PhoenixMiner.exe -pool ssl://eth-us-east.flexpool.io:5555 -pool2 ssl://eth-us-west.flexpool.io:5555 -wal 0x37d5F7d290dd5509CF5e2C5257689Ddd5c53f78D.Rig001 -logdir C:\Users\Peeps\Downloads\Tools\PhoenixMiner\logs -logsmaxsize 50
pause
```

**Comment by PeepsEZ** [comment]
Okay, that fixed it. I would still like to be able to see the mining window still. Just in case there are errors or just to see it. 

![delete](https://user-images.githubusercontent.com/14933388/105889268-fe11fb80-5fdb-11eb-8fd9-c6bc8bb63021.jpg)

**Comment by billiford** [comment]
Nice. I created the feature request to see the output of these batch scripts here: https://github.com/billiford/procswap/issues/6
